apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-frontend
  namespace: demo-app-frontend-dev
  labels:
    app: demo-app-frontend
    dxp.io/managed: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-frontend
  template:
    metadata:
      labels:
        app: demo-app-frontend
        backstage.io/kubernetes-id: demo-app-frontend
    spec:
      nodeSelector:
        role: workload
      tolerations:
      - key: role
        operator: Equal
        value: workload
        effect: NoSchedule
      containers:
      - name: demo-app-frontend
        image: harbor.harbor.svc.cluster.local/dxp/demo-app-frontend:266fe8b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-frontend
  namespace: demo-app-frontend-dev
spec:
  selector:
    app: demo-app-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP